### ISSUE TITLE
Incompatible with JobsAddon for LevelZ

### ISSUE THREAD

**Issue by sleepy343** [kltyton/stardewfishing-fabric#1]
Currently using the 1.20.1 version of the mods. When successfully fishing, you gain 0 job experience from the [JobsAddon](https://modrinth.com/mod/jobsaddon) for [LevelZ](https://modrinth.com/mod/levelz/versions). I haven't tested if it works without any other mods, but I know that I was gaining fishing experience just fine before adding this mod. Please add compatibility, both these mods are great.

**Comment by kltyton** [comment]
This was fixed in version 1.3.1
