### ISSUE TITLE
Game crashes when fishing.

### ISSUE THREAD

**Issue by SilasExperiment** [kltyton/stardewfishing-fabric#3]
I just wanted to test the fishing, I crashed right after it said "Hit!"
This is the log: https://mclo.gs/caW0zvv
If you need more info, like the modpack, respond to this and I will tell you everything I know.

**Comment by kltyton** [comment]
I have only tested this mod on version 1.20.1 of my world, and have not tested it on version 1.20.4. If I have time, I will test its performance on version 1.20.4 and fix these issues.

**Comment by kltyton** [comment]
This was fixed in version 1.20.4-1.3.1
